typography_spectrum: 0.60733
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4375
  lightness: 0.1282619454432279
  saturation: 0.875
  rhythmicContrast: 0.7770797447301447
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.29175
analytics:
  google: null
  facebook: null
  twitter: null
name: tomhunt
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: TomHunt
purpose: []
