name: tomhunt
favicon: null
layout_spectrum: 0.3848073261324316
typography_spectrum: 0.9051211813930422
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4347726295236498
  lightness: 0.1282619454432279
  saturation: 0.4693270653951913
  rhythmicContrast: 0.7770797447301447
purpose: []
